version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: tiktok_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tiktok_db
      MYSQL_USER: tiktok_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    container_name: tiktok_adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
